classes = [
   'Banh bao',
   'Banh beo',
   'Banh bot loc',
   'Banh can',
   'Banh canh',
   'Banh chung',
   'Banh cuon',
   'Banh duc',
   'Banh gio',
   'Banh hoi',

   'Banh khot',
   'Banh mi',
   'Banh pia',
   'Banh tet',
   'Banh tranh nuong',
   'Banh xeo',
   'Bun bo hue',
   'Bun cha ca',
   'Bun dau mam tom',
   'Bun man',

   'Bun rieu',
   'Bun thit nuong',
   'Ca kho to',
   'Canh chua',
   'Canh kho qua',
   'Cao lau',
   'Cha gio',
   'Chao long',
   'Chuoi',
   'Com cuon',

   'Com tam',
   'Com trang',
   'Goi cuon',
   'Hu tieu',
   'Mam chung',
   'Mi quang',
   'Muc xao chua ngot',
   'Nem chua',
   'Ngheu hap sa',
   'Pho',

   'Tom rim',
   'Xoi xeo'
]